# Generated by Django 2.1.1 on 2018-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='dId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='eFirstName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.AddField(
            model_name='employee',
            name='eLastName',
            field=models.CharField(default='Verma', max_length=100),
            preserve_default=False,
        ),
    ]
